import React from 'react'
import Head from 'next/head'

import { useState } from 'react'
import axios from 'axios'

function Contact() {

  const [email,setEmail]=useState('')
  const SendMail = async (e:any)=>{

    axios.post('http://localhost:3000/api/email',{email})
   .then(
    
   (res)=>{
     alert('Send Mail To You')
     setEmail('')
 
   }
 
   ).catch(
     (e)=>console.log(e)
   )
    e.preventDefault();
 console.log('call')
  }
  

  return (
    <div className="">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
   

    <main className="">
      <form>
     <input type="email" placeholder="Enter Mail" required value={email} onChange={(e)=>setEmail(e.target.value)}></input>
     <button onClick={SendMail}>Send</button>
       </form>
    </main>
  </div>)
}

export default Contact
 